<?php
include("header-01.html")
?>
        <section class="vasat">
        <span id="h">Series of Games</span>
        
        <div class="gameitem"><div class="gameitempic"><img  src="ax/ps-plus-extra-plan-thumbnail-01-12may22en.webp" alt=""></div><div><a href="" ><button>Plus Extra</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/ps-plus-premium-plan-thumbnail-01-12may22en-600x600.webp" alt=""></div><div><a href="" ><button>Plus Premium</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/ps-plus-essential-plan-thumbnail-01-12may22en-1536x1536.webp" alt=""></div><div><a href="" ><button>Plus Essential</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="pictures/elden.jpg" alt=""></div><div><a href="" ><button style="margin-left: 45px;">Elden ring</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/assassins creed valhalla.jpg" alt=""></div><div><a href="" ><button>AC Valhalla</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/20240309_153507_1509845565-400x400.jpg" alt=""></div><div><a href="" ><button>COD MW3</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/battlefield4-600x600.jpg" alt=""></div><div><a href="" ><button>Battlefield 4</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/20240309_122620_259067920-400x400.jpg" alt=""></div><div><a href="" ><button>The EvilWitHin</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/batel6.jpg" alt=""></div><div><a href="" ><button>Battlefield 6</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/20240309_153653_859510523-400x400.jpg" alt=""></div><div><a href="" ><button>Alan Wale</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/dmon-600x600.webp" alt=""></div><div><a href="" ><button>Demons souls</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/farcry6-deluxe-600x600.webp" alt=""></div><div><a href="" ><button style="margin-left: 55px;">Farcry 6</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/bloodborne-2.jpeg" alt=""></div><div><a href="" ><button>Blood borne</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/20240309_154038_1127670665-400x370.jpg" alt=""></div><div><a href="" ><button>Cyberpunk</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/doom.jpg" alt=""></div><div><a href="" ><button>Doom Eternal</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/Call-Of-Duty-Ghosts-modern-warfare-remastered-2-1-600x600.jpeg" alt=""></div><div><a href="" ><button>COD MW 1 old</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/call of duty mwii modern warfare ii.jpg" alt=""></div><div><a href="" ><button>COD MW 2</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/20240309_161315_1359566441-400x400.jpg" alt=""></div><div><a href="" ><button>Tsushima</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/god-of-war-3.png" alt=""></div><div><a href="" ><button>God of War 3</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/minecraft-600x600.webp" alt=""></div><div><a href="" ><button>Minecraft</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/Cyberpunk.jpg" alt=""></div><div><a href="" ><button>Cyberpunk</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/20240309_164955_1876886561-600x600.jpg" alt=""></div><div><a href="" ><button>COD Coldwar</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/fc-25-1721056518914-1-600x600.jpg" alt=""></div><div><a href="" ><button>FC 25</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/resident-evil-3.webp" alt=""></div><div><a href="" ><button>Resident Evil 3</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/wukong.png" alt=""></div><div><a href="" ><button>wukong</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/among-us-600x600.avif" alt=""></div><div><a href="" ><button>Among Us</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/dark_souls3_final_512_under_50kb.webp" alt=""></div><div><a href="" ><button>Dark Souls 3</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/origins-1-1-600x600.webp" alt=""></div><div><a href="" ><button>AC Origins</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/tusushema.jpg" alt=""></div><div><a href="" ><button>Tusushema</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/assassins-origins-600x600.webp" alt=""></div><div><a href="" ><button>AC Origins</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/Horizon_Forbidden_West-1-1-1-600x600.webp" alt=""></div><div><a href="" ><button>Horizon</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/mw2-400x400.png" alt=""></div><div><a href="" ><button>COD MW 2</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/call.jpg" alt=""></div><div><a href="" ><button>COD BO 6</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/astro-600x600.avif" alt=""></div><div><a href="" ><button>Astro Bot</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/JxilRmpXkS3CCXUnr0gZTBOlqso3plaw-600x600.jpg" alt=""></div><div><a href="" ><button>Dark Souls</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/rouge-600x600.webp" alt=""></div><div><a href="" ><button>AC Rouge</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/god of war 5.jpg" alt=""></div><div><a href="" ><button>Ragnarok</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/avatar.webp" alt=""></div><div><a href="" ><button>Avatar</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/hogwarts-400x400.jpg" alt=""></div><div><a href="" ><button>Hogwarts</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/ufc5-deluxe-400x400.png" alt=""></div><div><a href="" ><button>UFC 5</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/mortal1.png" alt=""></div><div><a href="" ><button>Mortal 1</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/batel1.jpg" alt=""></div><div><a href="" ><button>Battlefield 1</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/far-cry.jpeg" alt=""></div><div><a href="" ><button>Farcry Primal</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/untildawn-400x400.webp" alt=""></div><div><a href="" ><button>Untildawn</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/yotei.jpg" alt=""></div><div><a href="" ><button>Ghost of Yotei</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/black-flag-600x600.webp" alt=""></div><div><a href="" ><button>AC Black Falg</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/call of 4.jpg" alt=""></div><div><a href="" ><button>COD BO 4</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/syndicate-600x600.jpeg" alt=""></div><div><a href="" ><button>AC Syndicate</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/red dead 2.jpg" alt=""></div><div><a href="" ><button>Red Dead 2</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/advanced-400x400.png" alt=""></div><div><a href="" ><button>COD Advanced</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/forza-5-800x800.avif" alt=""></div><div><a href="" ><button>Forza 5</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/20240309_164452_1972267250-400x400.jpg" alt=""></div><div><a href="" ><button>CTR</button></a><span>50$</span></div></div>
       
        <div class="gameitem "><div class="gameitempic"><img  src="pictures/shadows.jpg" alt=""></div><div><a href="" ><button>AC Shadows</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/watch-dogs-legion-600x600.webp" alt=""></div><div><a href="" ><button>Watch Dogs</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/easportsfc_4064953b-1-1-600x600.jpg" alt=""></div><div><a href="" ><button>FC 24</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/odyssy.jpg" alt=""></div><div><a href="" ><button>AC Odyssy</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/pace.jpg" alt=""></div><div><a href="" ><button>Dead Space</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/fc26_compressed_high_quality.webp" alt=""></div><div><a href="" ><button>FC 26</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/resident-4-600x600.webp" alt=""></div><div><a href="" ><button>Resident 4</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/sekiro-400x353.jpg" alt=""></div><div><a href="" ><button>Sekiro</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/gta v.jpg" alt=""></div><div><a href="" ><button>GTA V</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/god-of-war.webp" alt=""></div><div><a href="" ><button>God OF War 4</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/mafia-the-okd-400x328.png" alt=""></div><div><a href="" ><button>Mafia</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/the-last-of-us1-2-1-800x800.webp" alt=""></div><div><a href="" ><button>TheLastOfUs1</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/hollow.jpg" alt=""></div><div><a href="" ><button>Hollow Knight</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/mortal-kombat-ultimate-400x353.jpg" alt=""></div><div><a href="" ><button>Ultimate</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/sifu-600x600.webp" alt=""></div><div><a href="" ><button>Sifu</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/witcher3-passgame.ir_-600x600.webp" alt=""></div><div><a href="" ><button>Witcher 3</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/mortal 11.jpg" alt=""></div><div><a href="" ><button>Mortal 11</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/dark-600x600.webp" alt=""></div><div><a href="" ><button>dark Souls3</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/M7D7jpMTkfpiZcMFdQhsseXr-600x600.webp" alt=""></div><div><a href="" ><button>Resident 2</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/unity-400x353.jpg" alt=""></div><div><a href="" ><button>AC Unity</button></a><span>50$</span></div></div>

        <div class="gameitem "><div class="gameitempic"><img  src="pictures/gta vi.png" alt=""></div><div><a href="" ><button>GTA VI</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/alan-wake-2-400x400.jpg" alt=""></div><div><a href="" ><button>Alan Wake 2</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/img02109.jpg" alt=""></div><div><a href="" ><button>AC Mirage</button></a><span>50$</span></div></div>   <div class="gameitem "><div class="gameitempic"><img  src="ax/Screenshot-2025-10-08-055355-400x400.png" alt=""></div><div><a href="" ><button>DS 2</button></a><span>50$</span></div></div>
    </section>
    </div>
</body>
</html>